services:
  api:
    container_name: gymmy-api
    build: ./gymmy-api
    restart: always
    ports:
      - 3001:3001
    env_file:
      - ./gymmy-api/.env
    volumes:
      - ./gymmy-api:/api
  ui:
    container_name: gymmy-ui
    build: ./gymmy
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./gymmy/.env
    volumes:
      - ./gymmy:/ui
    depends_on:
      - api